=== JaewooJung/spms/spms_jw/src/main/webapp/xml/books.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % basicElements "(author*,book*,press*)">

<!ENTITY % idAttr "id	ID #REQUIRED">

<!ENTITY hong "홍길동">

<!ELEMENT books %basicElements;>
<!ELEMENT author (name, email, tel?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ATTLIST author
	id ID #REQUIRED
	gender CDATA #IMPLIED
	country (local | internal) "local">
<!ELEMENT book 
(title,press,page?,price,published?,edition?,author+,(in | out))>
<!ELEMENT title (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT published (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT in EMPTY>
<!ELEMENT out EMPTY>

<!ATTLIST book
	isbn ID #REQUIRED
	authors IDREFS #REQUIRED
	press IDREFS #REQUIRED>

=== JaewooJung/spms/spms_jw/src/main/webapp/xml/test02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books>
	<author id="A001" gender="male">
		<name>&hong</name>
		<email>hong@test.com</email>
		<tel>111-2222</tel>
	</author>
	<author id="A002" country="internal">
		<name>홍길동</name>
		<email>hong@test.com</email>
	</author>
	<book isbn="K1002">
		<title>오호라 자바 프로그래밍</title>
		<press>비트출판사</press>
		<price>20000</price>
		<in />
	</book>

	<book isbn="K1003" authors="A001 A002" press="A001">
		<title>오호라 자바 웹 프로그래밍</title>
		<price>20000</price>
		<in />
	</book>
	
	<press id="P001">
	<name>비트출판사</name>
	<email>help@bitbook.com</email>
	<tel>111-3333</tel>
	</press>
</books>
